# Generated by Django 3.2.1 on 2021-05-05 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='(empty)', max_length=256)),
                ('starting_at', models.DateTimeField()),
                ('password', models.CharField(blank=True, max_length=512, null=True)),
                ('attendants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
